spring.application.name=crudSpringBootDemo
spring.application.name=cruDtoDemo

spring.datasource.url=jdbc:mysql://localhost:3306/student_crud_db_4
spring.datasource.username=root
spring.datasource.password=960460

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true